language: rust

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - nightly

before_deploy:
  - cargo build --release

deploy:
  provider: releases
  api_key:
    secure: DzHaRbvQamls//Cb8CBZwMDvTFQKB5gVKsl/Pz0x5mWkpvLS6cb9dvsP6ztp9HYwAdFhfRrnL1YDOFVfcg/JBSl4I8jl0kUfA4GkfpF1kLqyT/wq/iwUMqzJu/so4VIP4dOZTDLyfb/PCXP1f2AWZWzNp2YvM6u2dvuo8LWYxoqNHBR3r0grnayiRnfmva9SnyeoGFQ0sT5FlOy7h+rScsU1hua6Qhxr7lwGFHWZ95iOltYjKFHbZVMsQP/fYEBczHYCSEcCAUhAtWt2CmyFokNgCTKLCW/pukOgg2UrnYN+hqRR6dy7vp3cPLUcoPkusNFDAX+AZUHP2QtU3mhWrYKOuHq3gweD7BRCMIANnbqJrN3jlLuEsbf/ydfkBf3NINBSpweea+3KPmGusqikQYZkOddhRjDjmE+3fNrxEZgvUEU5Z+kwsdvGrdQCHVHJ+7hTKN6IJVZS+14pQQQyHhQmKqrlYyHbbDcl4lm419G2Mhxa1xk4eMQRpKvmdHczis5UZoJNNgWz/gO7X3JG40UJTGKLF8IDPH4/AlYJ1VqmecSn4dNIER+nab++yLks6g+TexlhGYn9PrdwWFfFB3IeTIM7E4vIHgwMqjYpUwBDZ1YWNbCLMRrACqBxt+fIKLOPr3s1sUXiPXUlzBQMPEJ1xPGs1FxFyN6rstH2qAI=
  file: target/release/jors
  skip_cleanup: true
  on:
    repo: ys-nuem/jors
    all_branches: true
    tags: true
